export default {
  inputText  : require('./input-text.vue').default,
  inputTextarea  : require('./input-textarea.vue').default,
  inputColor  : require('./input-color.vue').default,
  inputRadio  : require('./input-radio.vue').default,
  inputImage  : require('./input-image.vue').default,
  inputDate  : require('./input-date.vue').default,
  inputWheel  : require('./input-wheel.vue').default,
  inputCheckbox  : require('./input-checkbox.vue').default,
  inputFont  : require('./input-font.vue').default,
  inputNumber  : require('./input-number.vue').default,
  inputImageShowMode  : require('./input-image-style.vue').default,
  inputSwipeStyle : require('./input-swipe-style.vue').default,
  inputEmployee : require('./input-employee.vue').default,
  inputVideo: require('./input-video.vue').default,
}
